In [1]:
import numpy as np
import pandas as pd

In [3]:
print(np.__version__)

1.21.5


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
import numpy as np

arr = np.array(42)

print(arr.shape)

()


In [8]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])

print(arr1.shape)

(5,)


In [10]:
import numpy as np

arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr2.shape)

(2, 3)


In [12]:
import numpy as np

arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr3.shape)

(2, 2, 3)


In [13]:
#Number of dimensions

In [14]:
print(arr.ndim,arr1.ndim,arr2.ndim,arr3.ndim)

0 1 2 3


In [16]:
import numpy as np

array = np.array([1, 2, 3, 4], ndmin=5)

print(array)
print('number of dimensions :', array.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [32]:
#Accessing elements

for i in range(len(arr2)):
    for j in range(len(arr2[0])):
        print(arr1[j])

1
2
3
1
2
3


In [37]:
#slicing 
arr1[0:4:2] #start:end:step

array([1, 3])

In [38]:
arr1[-3:-1]

array([3, 4])

In [43]:
arr2[0,1:5
    ]

array([2, 3])

In [44]:
#Data Types

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [45]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [46]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [47]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [48]:
arr3.reshape(3,4)

array([[1, 2, 3, 4],
       [5, 6, 1, 2],
       [3, 4, 5, 6]])

In [52]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [55]:
arr.reshape(2,4).base

array([1, 2, 3, 4, 5, 6, 7, 8])

In [57]:
arr3.reshape(3,4).base

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [59]:
arr3.reshape(6,2).base

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [60]:
#flatten

In [61]:
arrflat = arr3.reshape(-1)

In [62]:
arrflat

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [63]:
#Iterating on arrays:

In [64]:
for x in np.nditer(arr3):
  print(x)

1
2
3
4
5
6
1
2
3
4
5
6


In [66]:
#Iterating on every 2nd element
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [67]:
import numpy as np

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [69]:
#Combine 2 1D arrays:

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [73]:
#Join 2D arrays along rows (axis 1) or simply combine (axis 0)

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [74]:
#Join 2D arrays along the column axis - Stacking

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [75]:
#Stacking can also be done along rows - hstack

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [76]:
#Another stacking dimension - Height

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [79]:
#Splitting

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0],newarr[2])

[1 2] [5 6]


In [80]:
#Find where
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [81]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


In [82]:
#Sort - Self explanatory except for bool, where False is a lower value
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [86]:
#Random

from numpy import random

#Generate arrays of random integers between 0 and 100
randarr = random.randint(100, size=(3,4))
randarr

array([[80,  1, 34,  5],
       [55,  5,  2, 17],
       [59, 97, 64, 52]])

In [88]:
#Generate arrays of random floats
randfloats = random.rand(3,4)
randfloats

array([[0.13292419, 0.13671615, 0.28509771, 0.45426743],
       [0.20280813, 0.86803896, 0.58771075, 0.41817406],
       [0.39479995, 0.56342344, 0.52559629, 0.28378581]])

In [89]:
x = random.choice([3, 5, 7, 9])

print(x)

5


In [93]:
arrchoice = random.choice([1,4,6,2,7,8],size = (3,4))
arrchoice

array([[1, 7, 1, 1],
       [1, 4, 4, 1],
       [8, 4, 2, 1]])

In [ ]:
#Simple arithmetic

In [102]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]

addition = np.add(x, y)
sub = np.subtract(x,y)
multiplication = np.multiply(x,y)
div = np.divide(x,y)
modulus = np.mod(x,y) #also np.remainder
exp = np.power(x,y)
quotient_and_modulus = np.divmod(x,y)

print(addition,sub,multiplication,div,modulus,exp,quotient_and_modulus)

[ 5  7  9 11] [-3 -3 -3 -3] [ 4 10 18 28] [0.25       0.4        0.5        0.57142857] [1 2 3 4] [    1    32   729 16384] (array([0, 0, 0, 0]), array([1, 2, 3, 4]))


In [103]:
#Rounding

floating_array = [3.667,2.341]

truncated = np.trunc(floating_array)
truncated

array([3., 2.])

In [105]:
fixed = np.fix(floating_array)
fixed

array([3., 2.])

In [107]:
rounded_by_x = np.around(floating_array,2)
rounded_by_x

array([3.67, 2.34])

In [109]:
floored = np.floor(floating_array)
floored

array([3., 2.])

In [110]:
ceiled = np.ceil(floating_array)
ceiled

array([4., 3.])